version: '3.9'

# name the resulting compose project after the name of the instance
# this enables us to easily host multiple instances on a single machine
name: ${INSTANCE_NAME:-self-hosted-api-trader-game}

services:
  traefik:
    image: 'traefik:v3.2.1'
    container_name: 'Reverse-Proxy'
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.trader-game.acme.tlschallenge=true'
      - '--certificatesresolvers.trader-game.acme.storage=/letsencrypt/acme.json'
      # change the email address to your own
      - '--certificatesresolvers.trader-game.acme.email=owner@your-domain.com'
    ports:
      - 443:443
    depends_on:
      - backend
      - frontend
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'letsencrypt:/letsencrypt'
    networks:
      - internal

  backend:
    image: ghcr.io/maybeanerd/selfhosted-api-trader-game-backend:0.1.23
    restart: always
    depends_on:
      - database
    networks:
      - internal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.backend.loadbalancer.server.port=8080'
      # The domain and path the service will respond on, change this to your domain
      - 'traefik.http.routers.backend.rule=Host(`your-domain.com`) && PathRegexp(`\/(api|\.well-known).*`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=trader-game'
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}
      - DATABASE_HOST=database
      # The base URL of the backend, change this to your domain
      - BASE_URL=https://your-domain.com

  frontend:
    image: ghcr.io/maybeanerd/selfhosted-api-trader-game-frontend:0.1.23
    restart: always
    depends_on:
      - backend
    networks:
      - internal
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}
      - DATABASE_HOST=database
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.frontend.loadbalancer.server.port=3000'
      # The domain and path the service will respond on, change this to your domain
      - 'traefik.http.routers.frontend.rule=Host(`your-domain.com`) && PathPrefix(`/`)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=trader-game'

  database:
    image: postgres:16.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
    restart: always
    networks:
      - internal
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  letsencrypt:

networks:
  internal:
