export enum ResourceType {
  STONE = 'stone',
  WOOD = 'wood',
  IRON = 'iron',
  GOLD = 'gold',
  DIAMOND = 'diamond',

  // generated by chat GPT
  /* SILVER = 'silver',
  COPPER = 'copper',
  TIN = 'tin',
  COAL = 'coal',
  LEAD = 'lead',
  BRONZE = 'bronze',
  BRASS = 'brass',
  ALUMINIUM = 'aluminium',
  SAND = 'sand',
  GLASS = 'glass',
  LEATHER = 'leather',
  CLOTH = 'cloth',
  WOOL = 'wool',
  SILK = 'silk',
  FUR = 'fur',
  FOOD = 'food', // Not sure if this is too unspecific, or even in general a good idea?
  WATER = 'water',
  OIL = 'oil',
  GASOLINE = 'gasoline',
  ELECTRICITY = 'electricity',
  MEDICINE = 'medicine',
  TIMBER = 'timber',
  PAPER = 'paper',
  PLASTICS = 'plastics',
  CHEMICALS = 'chemicals', // pretty sure this is not good enough
  RUBBER = 'rubber',
  PRECIOUS_STONE = 'precious_stone', // LOL this could be the money resource?
  SPICE = 'spice',
  SALT = 'salt',
  SUGAR = 'sugar', */
}

/**
 * Ideas to combine resources:
 * 
 *
Wood is required to make paper.
Sand is required to make glass.
Coal is required to smelt iron ore into iron.
Iron is required to make steel.
Diamond-tipped tools are required to mine certain types of stone.
Copper is required to conduct electricity.
Water is required for irrigation to grow crops.
Oil is required to produce gasoline.
Gasoline is required to power vehicles and machinery.
Precious stones are required for jewelry-making.
Leather is required to make shoes and armor.
Wool and silk are required to make clothing.
Timber is required for construction.
Chemicals are required to make medicines.
Rubber is required for tire production.

Salt is required to preserve food.
Sugar is required to make certain types of food and drinks.
Aluminum is required to make cans for storing food and beverages.
Glass is required to make bottles for storing liquids.
Cotton is required to make clothing and textiles.
Lumber is required to build ships and boats.
Marble and granite are required for construction and architecture.
Zinc is required for galvanization of iron and steel.
Silver and gold are required for coin production.
Platinum is required for certain types of high-tech manufacturing.
Titanium is required for certain types of aircraft and spacecraft manufacturing.
Petroleum is required to produce plastic and synthetic materials.
Corn and other grains are required to produce ethanol, which is used as a fuel additive.
Nickel is required to make stainless steel.
Cobalt is required for certain types of high-tech manufacturing.

Own ideas:
Paper is required to sign contracts: to automate trading

Wood will enable carts and wheels so that trades can be finished faster, and have more capacity
It could also enable ships later on
Similarly tires could enable cars, or electricity and steam power/coal could enable trains


Chat GPT ideas:
In order to promote trading between villages/players, it's a good idea to make certain resources scarce in some areas and more abundant in others. This will encourage players to trade with each other to obtain the resources they need to grow and develop their villages. Here are some suggestions for basic resources and how you could make them scarce:

Wood: This could be the most abundant resource, as it is available in most areas of the game world. However, you could make it scarce in certain regions that have been heavily deforested, or in areas that are too dry or too cold to support dense forests.

Stone: This could be another fairly common resource, but you could make it scarce in regions that lack natural rock formations or have already been heavily mined.

Water: While water may not be a resource that players can trade directly, you could make it scarce in regions that are prone to droughts, or in areas where water pollution is a problem. This would make it difficult for players to grow crops and sustain their villages without trading for water.

Food: You could make certain types of food scarce in different regions, depending on the climate and soil conditions. For example, wheat may be abundant in fertile river valleys, while fish may be scarce in landlocked regions.

Metals: Different types of metals could be scarce in different regions, depending on the geology and availability of mineral resources. For example, iron may be abundant in some regions but scarce in others, while gold and silver may be found in limited quantities only in certain areas.

Fuel: Depending on the technological level of your game world, different types of fuel could be scarce in different regions. For example, coal may be abundant in some regions but scarce in others, while regions without access to fossil fuels may rely heavily on wood or biofuels.

To determine the weighting of each resource, you could consider factors such as the overall availability of the resource in your game world, the importance of the resource to the game mechanics, and the relative value of the resource to players. You could also adjust the scarcity of resources over time, based on player actions and events in the game world.
 */
