export enum Resource {
  STONE = 'stone',
  WOOD = 'wood',
  IRON = 'iron',
  GOLD = 'gold',
  DIAMOND = 'diamond',

  // generated by chat GPT
  /* SILVER = 'silver',
  COPPER = 'copper',
  TIN = 'tin',
  COAL = 'coal',
  LEAD = 'lead',
  BRONZE = 'bronze',
  BRASS = 'brass',
  ALUMINIUM = 'aluminium',
  SAND = 'sand',
  GLASS = 'glass',
  LEATHER = 'leather',
  CLOTH = 'cloth',
  WOOL = 'wool',
  SILK = 'silk',
  FUR = 'fur',
  FOOD = 'food', // Not sure if this is too unspecific, or even in general a good idea?
  WATER = 'water',
  OIL = 'oil',
  GASOLINE = 'gasoline',
  ELECTRICITY = 'electricity',
  MEDICINE = 'medicine',
  TIMBER = 'timber',
  PAPER = 'paper',
  PLASTICS = 'plastics',
  CHEMICALS = 'chemicals', // pretty sure this is not good enough
  RUBBER = 'rubber',
  PRECIOUS_STONE = 'precious_stone', // LOL this could be the money resource?
  SPICE = 'spice',
  SALT = 'salt',
  SUGAR = 'sugar', */
}

/**
 * Ideas to combine resources:
 * 
 *
Wood is required to make paper.
Sand is required to make glass.
Coal is required to smelt iron ore into iron.
Iron is required to make steel.
Diamond-tipped tools are required to mine certain types of stone.
Copper is required to conduct electricity.
Water is required for irrigation to grow crops.
Oil is required to produce gasoline.
Gasoline is required to power vehicles and machinery.
Precious stones are required for jewelry-making.
Leather is required to make shoes and armor.
Wool and silk are required to make clothing.
Timber is required for construction.
Chemicals are required to make medicines.
Rubber is required for tire production.

Salt is required to preserve food.
Sugar is required to make certain types of food and drinks.
Aluminum is required to make cans for storing food and beverages.
Glass is required to make bottles for storing liquids.
Cotton is required to make clothing and textiles.
Lumber is required to build ships and boats.
Marble and granite are required for construction and architecture.
Zinc is required for galvanization of iron and steel.
Silver and gold are required for coin production.
Platinum is required for certain types of high-tech manufacturing.
Titanium is required for certain types of aircraft and spacecraft manufacturing.
Petroleum is required to produce plastic and synthetic materials.
Corn and other grains are required to produce ethanol, which is used as a fuel additive.
Nickel is required to make stainless steel.
Cobalt is required for certain types of high-tech manufacturing.

Own ideas:
Paper is required to sign contracts: to automate trading
 */
